name: Full Pipeline

on:
  push:
    branches: [ "master" ]
    
jobs: 
  set-vars:
    name: Set Variables
    runs-on: ubuntu-latest
    outputs:
      environment: test
    steps:
      - run: echo "Exposing env vars"

  infra-test-environment: 
    name: Infra Test
    uses: ./.github/workflows/terraform.yml
    with:
      environment: ${{ needs.vars.outputs.environment }}
    
