name: Full Pipeline

on:
  push:
    branches: [ "master" ]
    
jobs: 
  infra-test-environment: 
    runs-on: ubuntu-latest
    environment: test
    defaults:
      run:
        working-directory: './infra/environments/test'
    steps:
      - uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}
      - run: terraform init
