name: Full Pipeline

on:
  push:
    branches: [ "master" ]
    
jobs: 
  infra-test-environment: 
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Infra Test
        uses: ./.github/workflows/terraform.yml
        with:
          environment: ${{ vars.ENV_NAME }}
    
