name: Full Pipeline

on:
  push:
    branches: [ "master" ]
    
jobs: 
  infra-test-environment: 
    concurrency: test-environment
    runs-on: ubuntu-latest
    environment: test
    defaults:
      run:
        working-directory: './infra/environments/test'
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}
      - run: terraform init
      - name: create tfvars file
        uses: DamianReeves/write-file-action@master
        with:
          path: ./infra/environments/test/test.tfvars
          write-mode: overwrite
          contents: |
            discord_token="${{ secrets.DISCORD_TOKEN }}"
            postgres_password="${{ secrets.POSTGRES_PASSWORD }}"
            aws_access_key="${{ vars.AWS_TOKEN_USERNAME }}"
            aws_access_secret="${{ secrets.AWS_TOKEN_PASSWORD }}"

      - name: terraform plan
        run: terraform plan -no-color -var-file="test.tfvars"

      - name: terraform apply
        if: ${{ steps.plan.outputs.exitcode }} = 2
        run: terraform apply -no-color -input=false -var-file="test.tfvars"
        
