on:
  workflow_call:
        
jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@master
    
    - name: Terraform Init
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.13
        tf_actions_subcommand: 'init'
        tf_actions_working_dir: "./infra/${{ vars.ENV_NAME }}"
        tf_actions_comment: true
        
    - name: Terraform Plan
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.13
        tf_actions_subcommand: 'plan'
        tf_actions_working_dir: "./infra/${{ vars.ENV_NAME }}"
        tf_actions_comment: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TF_VAR_discord-token: ${{ secrets.DISCORD_TOKEN }}
        TF_VAR_postgres-password: ${{ secrets.POSTGRES_PASSWORD }}
        TF_VAR_aws-access-key: ${{ vars.AWS_TOKEN_USERNAME }}
        TF_VAR_aws-access-secret: ${{ secrets.AWS_TOKEN_PASSWORD }}
        
        
  
